### PR TITLE
Adding ExceptionResource

### PR DESCRIPTION
**Pull request by bigpaulie**
Hello, I have added a new resource.
I've found myself in the situation where I needed to maintain the same response format uniform across my API and in order to do so I need to be able to serialize Exceptions as well as other resources.

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
This strikes me as something that should be managed by the serializer implementation rather than being a first class resource type the same way "links" are for the `JsonApiSerializer`.

So you'd do something like `return $this->item(new Exception('foo'));` and have a transformer that did something like:

```php
function (Exception $exception) {
    return [
        'errors' => [
            [
                'message' => $exception->getMessage(),
                ...
            ]
        ]
    ];
}
```

Now your serializer can do `if (isset($data['errors'])) { ... }` to format it properly.

This is ideal because it gets us away from locking down to one specific format or another. Is this a suitable solution for what you're wanting to do, or is there something more that this pull request enables that I'm not seeing?

**Comment by matthewtrask** [comment]
Im currently agreeing with @KorvinSzanto on this, but curious to see what happens.

**Comment by bigpaulie** [comment]
Hello, I'm sorry for my late response. 
In my opinion succes responses and errors must be formatted uniformly across the application. 

It make more sense to me to segregate the resources just like the SOLID principle states.

This resource has a single responsibility, it's open for extension and so on and so forth. 

What @KorvinSzanto says also makes sense in a way. But from my point of view this is the correct approach. 

If you think about it in a framework agnostic way, typically the item and collection resources are usually representations of database models. 

Whilst Errors or Exceptions represent a different data type.

If you choose to close this pull request without merging it it's totally ok. Users will always have the solution proposed by you.

Thank you very much for your time !
Best regards, 
Paul.

**Comment by KorvinSzanto** [comment]
I'm still not sure, I'm going to let this PR stay open for awhile and decide when we're closer to a 1.0 releae

**Comment by johannesschobel** [comment]
Dear all,
i am writing this comment from a "i use Fractal within a framework context and **not** pure vanilla Fractal" point-of-view.

Most frameworks (e.g., Laravel (PHP), NestJS (TypeScript), Express (JavaScript), ...) have a designated place to catch all Errors / Exceptions thrown in the application. So this functionality should be provided "next" to the normal serialization process. However, it could be benefitial to just use the same methods as already defined.

However, in order to make it more clear that this specifically tackles errors, i would give this method an explicit `error()` name. Internally, however, it can call the `item()` method. However, this may also raise additional questions - what about a "list of errors"? Consider, for example, this use-case:
* A user fills in a form and submits it to the API
* The API responds with an `ExceptionBag` containing `ValidationExceptions` for each error found. For example:
   * The `email` is not a valid email-address
   * The `username` has already been taken
   * `password` and `password_confirmation` do not match

In this case you should return a list of exceptions. Would this be an `ErrorBagException` so you call the `item()` method? Or would this be a list of `ValidationExceptions` and you call the `collection()` method?

Just some additional questions here :thinking: 
All the best

**Comment by KorvinSzanto** [comment]
>  Would this be an ErrorBagException so you call the item() method? Or would this be a list of ValidationExceptions and you call the collection() method?

This would depend on how your transformer is implemented, it could be either.


I don't think I can see the benefit to having a custom type for exceptions and errors at this moment, in my opinion it will lead to a more confusing API. Instead one can just use items, collections, and transformers to handle this like you'd do with any other type of data flowing out. Going the other route and giving exceptions a first class status will lead us down the road of having types for all kinds of item types that I don't really want to get into like links or files.

If there are points I'm failing to see or examples of things that are impossible to do with the way things are currently set up I'm happy to reopen and reconsider.

**Pull request closed without merging**
