### PR TITLE
Move to Github Actions

### PR DESCRIPTION
**Pull request by JustSteveKing**
Hey all 👋 

So after seeing the issue about moving to Github actions I thought I would drop in a PR. I have tried to keep this as "vague" as possible incase you want to push any of these upstream. I have matched the travis support back to PHP 5.4 for now.

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
Would it be better to have different jobs for testing and for CI? The benefits of that are that we'd see both code style and tests even if code style failed and we'd be able to see at a glance which parts failed.

**Comment by JustSteveKing** [comment]
While I'd usually agree, the point of this PR was to migrate like for like from travis over to GitHub Actions 🙂

It begs the question, should code quality and tests be separated. If this is the case I would look to move the code quality checks to it's own workflow file instead of a separate job. 

I'm open to opinions on this, and will happily refactor to whatever the concensus is here.

**Comment by JustSteveKing** [comment]
@KorvinSzanto here we go! I have moved them to separate workflos now 😄

**Comment by JustSteveKing** [comment]
@matthewtrask all done now buddy!

**Comment by KorvinSzanto** [comment]
:+1: Nice, I think the last steps for this to be a complete replacement would be to move the bit in .travisci that copies coverage up to scrutinizer into the tests and drop the .travisci file

**Comment by JustSteveKing** [comment]
@KorvinSzanto that would be super easy to do, and I did it in the beginning, but it kept 404-ing because it ran on my repo 😂

Will get that added in the morning for you

**Comment by JustSteveKing** [comment]
@KorvinSzanto here we go! It may fail to build on my local branch now but scrutinizer steps have been added, as has the updated github action readme badge - so when merged the status should swap.

**Review by KorvinSzanto — APPROVED** [review]

**Pull request merged**
