### PR TITLE
Test against php 8.0

### PR DESCRIPTION
**Pull request by sergiy-petrov**

### CODE REVIEW

**Review by willishq — APPROVED** [review]

**Comment by matthewtrask** [comment]
it looks like the tests for php 8 have failed, can you add 8 to the allowed-failures for the time being until we get time to update the package?

**Comment by sergiy-petrov** [comment]
@matthewtrask i tried to resolve this issue by requiring phpunit ^9.3 in composer.json but it seems it's impossible to have php 5.4 and 8.0 support at the same time (because phpunit ^9.3 forces you to use :void typehint in setUp() method, but typehints are not supported in older versions of php). 

What do you think about dropping legacy php version in the next major version of the package? I can PR that

**Comment by willishq** [comment]
I fully advocate the removal of legacy versions of PHP from our supported versions, PHP 7.2 is currently the latest version to reach EOL. PHP 5.4 has not been supported for almost 6 years. Realistically I think the minumum version requirement for the next major version should be 7.4.

**Comment by JustSteveKing** [comment]
I think by the time a new major version is released, PHP will be phasing out 7.4?

**Review by Nyholm — APPROVED** [review]
I suggest to merge and fix the issues in the following PR. 

Related to #533

**Review by matthewtrask — APPROVED** [review]

**Pull request merged**
