### PR TITLE
Enhancement: Send builds to container-based infrastructure

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] sends builds to container-based infrastructure

### CODE REVIEW

**Comment by Ilyes512** [comment]
@localheinz
Scrutinizer should work now, but PR's opened before this fix https://github.com/thephpleague/fractal/pull/212 need to be rerun (on Travis you will see a refresh button on the PR's build page. On can only do that if you got write access to the repo).

**Comment by localheinz** [comment]
Thank you, @Ilyes512!

**Comment by Ilyes512** [comment]
@localheinz Your welcome :) Your other 3 PR's where successful, but this one isn't? Perhaps you didn't rebase before, but after refreshing?

**Comment by localheinz** [comment]
@willishq 

Done!

**Pull request merged**
