### PR TITLE
Add Resource getter in Scope

### PR DESCRIPTION
**Pull request by webda2l**
Useful in some cases. Thanks.

### CODE REVIEW

**Comment by hskrasek** [comment]
@webda2l What would be the use of this exactly? Wouldn't you already have access to the resource stored on the scope, since you have to pass resource into the fractal manager which creates the scope?

**Comment by webda2l** [comment]
For now, in my controller, my collection action is minimal:

````
public function collectionAction(Request $request, $version, $resourceKey)
{
    $resourceManager = $this->get('api.resource_registry')
           ->getResourceManager($version, $resourceKey);

    // Validate request params, query Data and return fractal Collection
    $data = $resourceManager->getDataCollection($request);
    return new JsonResponse($data->toArray());
}
````

I need getResource() to access getPaginator() and add extra header params:

````
public function collectionAction(Request $request, $version, $resourceKey)
{
    $resourceManager = $this->get('api.resource_registry')
           ->getResourceManager($version, $resourceKey);

    // Validate request params, query Data and return fractal Collection
    $data = $resourceManager->getDataCollection($request);
    return new JsonResponse($data->toArray(), , 200, array(
        'X-Total-Count' => $data->getResource()->getPaginator()->getNbResults()
    ));
}
````

This being, my implementation is not finalized and it's possible that I'll refactor this part.
But this is my case for now, and maybe some other people can have the same..?..

**Comment by hskrasek** [comment]
@webda2l I think what you are saying makes sense. Not how I usually setup my applications, so confused me for a moment. Don't see an issue in adding this

**Comment by webda2l** [comment]
Rebased, any thoughts?

**Comment by willishq** [comment]
could you write a test for this please?

**Comment by webda2l** [comment]
Test added

**Pull request merged**
