### PR TITLE
Allow setting data + transformer outside of constructor

### PR DESCRIPTION
**Pull request by elliotfehr**

### CODE REVIEW

**Comment by philsturgeon** [comment]
What is the use case for doing this? Do you have the code?

**Comment by elliotfehr** [comment]
@philsturgeon This allows dependency injecting a Collection or Item object into another class and dynamically setting these properties.

**Comment by philsturgeon** [comment]
Got some code example there? :)

-- 
Phil

**Comment by gaomd** [comment]
@philsturgeon I was exactly expecting these two setters, here's the example.

Instead of...

```php
    public function show($userId, Manager $fractal)
    {
        $resource = new Item($this->user, new UserTransformer());

        return response()->json($fractal->createData($resource)->toArray());
    }
```

...I could just dependency injecting it in Laravel 5...

```php
    public function show($userId, Manager $fractal, Item $item, UserTransformer $userTransformer)
    {
        $resource = $item->setData($this->user)->setTransformer($userTransformer);

        return response()->json($fractal->createData($resource)->toArray());
    }
```

By this way, we should make the parameters of constructor of `Item`/`Collection` optional.

**Comment by elliotfehr** [comment]
@gaomd I completely agree. I've added the optional constructor arg as part of the PR.

**Comment by philsturgeon** [comment]
Sorry that took a while, Travis was playing silly buggers.

**Comment by gaomd** [comment]
I think we should make the `$data` parameter should be optional, otherwise the code example above won't work.

Under the hood, in the `fireTransformer` method, there is currently no `null` checking against `Transformer` object and `$data` array, maybe this should be a documentation issue.

**Pull request merged**
