### PR TITLE
Add shortcut functions

### PR DESCRIPTION
**Pull request by whoan**
Adds `transformToArray` and `transformToJson`. `createData` doesn't seem a very expressive method name to me.

### CODE REVIEW

**Comment by whoan** [comment]
I can write the tests if you like my suggestion.

**Comment by greydnls** [comment]
I'm not really sure it's necessary, to be honest. I don't find a big pain point from the extra function call. If I'm wrong and other people feel this pain and would like to see this integrated, I'd be willing to reconsider.

**Comment by vTripes** [comment]
I think keeping `createData` is fine, because instead of immediatly returning the data to array or to string, you can return a scope and then pass it to a controller or whatever else that needs to use a specific format.
IMO, this is not needed.

**Comment by whoan** [comment]
@vTripes I agree we should keep `createData`, my PR just add new methods.

**Comment by fabiocarneiro** [comment]
unit tests?

**Pull request closed without merging**
