### PR TITLE
feature(requirements)! : allow to work with php 8

### PR DESCRIPTION
**Pull request by michaoj**
- BREAKING CHANGE : Set php .8 as minimum version

### CODE REVIEW

**Review by michaoj — COMMENTED** [review]
Just to merge

**Comment by michaoj** [comment]
Wrong push

**Comment by patrick-radius** [comment]
Why the close?

**Comment by michaoj** [comment]
> Why the close?

I made a PR to the wrong repository : I did a quick fork to try to fix thing but didn't add any tests

**Pull request closed without merging**
