### PR TITLE
Add stale bot

### PR DESCRIPTION
**Pull request by Nyholm**
We use the same at Guzzle. 
Needs to be configured from: https://github.com/apps/stale

### CODE REVIEW

**Comment by matthewtrask** [comment]
hey @colinodell do you have admin rights for the League Org to add StaleBot to this repo?

**Comment by colinodell** [comment]
Yep, I do have admin rights, and it looks like it's currently enabled for all repositories in the org :) Feel free to ping me if you run into any issues or if I can assist further.

**Comment by matthewtrask** [comment]
fantastic, thank you so much @colinodell!

**Review by matthewtrask — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you for merging. 

I created some labels. Lets see if the bot is working. Im not sure if it is supposed to take a day or two

**Pull request merged**
