### PR TITLE
Static analysis with PHPStan

### PR DESCRIPTION
**Pull request by lookyman**
EDIT: This would be much easier if we could drop support for PHP <7. But I'll try to fix that build asap..

### CODE REVIEW

**Comment by fesor** [comment]
Why phpstan but not psalm?

**Comment by lookyman** [comment]
Because I am familiar with it.

**Comment by willishq** [comment]
I'm fine to merge this but I have one question: Why not have it in our `composer.json` as a dev dependency?

I can't see a reason for it not to be there, it means that everybody working on the project uses the same build / testing tools too.

If you want to make it a dev requirement then I'll merge it right away.

**Comment by lookyman** [comment]
Can't have it in composer because PHPStan requires PHP 7.1..

**Comment by matthewtrask** [comment]
We will be looking at getting this merged, and moving up to 7.2 as a minimum.

**Comment by lookyman** [comment]
Thanks! Shall I update it for the new PHPStan?

**Comment by matthewtrask** [comment]
@lookyman lets wait til we get the project up to 7.2 then yes, lets get this updated and using composer.

**Comment by lookyman** [comment]
@matthewtrask Sure, just ping me here when you need me, I'll be happy to help.

**Comment by KorvinSzanto** [comment]
If you'd like to reopen this on the [1.0.x branch](https://github.com/thephpleague/fractal/tree/1.0.x) we're probably ready to merge this

**Pull request closed without merging**
