### PR TITLE
JsonAPI: Including one level of `linked` data

### PR DESCRIPTION
**Pull request by renan**
Continuation of https://github.com/thephpleague/fractal/pull/126#issuecomment-63635216

Right now it only includes one level deep of `linked` data.
It is damn hard to have it all, especially when you consider #125 and you no longer have an array of item but a single item.

I think some refactoring would need to be done in order to have it nailed, starting on Manager and Scope.  One depending on each other makes things harder.
The Serializer would need to keep track of included/linked data, from top to bottom, so it can ensure uniqueness.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Can you pull recent changes and update any conflicts, then I'll get this merged. I waited a while because I planned to tackle this myself, but your solution looks good to me.

**Comment by renan** [comment]
Done.

But looking at the spec again they seem to have changed it. Instead of having:
```
'links' => array(
    'author' => 1,
),
```

It seems the new spec is:
```
'links' => array(
    'author' => array(
        'linkage' => array(
            'type' => 'author',
            'id' => 1,
        ),
    ),
),
```

A **lot** more verbose.
May not be a very good format to support until they don't tag a version I would say.

**Comment by philsturgeon** [comment]
Yeah, I might just wait until they’re done and then implement it fresh. Yay for dev releases!

-- 
Phil

**Comment by shabushabu** [comment]
According to their [status page](http://jsonapi.org/status/) they're on RC3 atm and will only make very small tweaks from now on. Sounds like it's ok to tackle it already. Also, one of the contributors for JSON API posted this relevant [comment](https://github.com/FriendsOfSymfony/FOSRestBundle/issues/452#issuecomment-81962347) on the FOSRestBundle repo.

**Comment by webda2l** [comment]
There are some trouble with new linkage specification https://github.com/json-api/json-api/issues/623.
Maybe this current PR could be merge to avoid current limitation of one level if discussion of new JsonAPI specification take time..

**Comment by jasonlewis** [comment]
We've now merged an improved JSON API serializer.

**Comment by renan** [comment]
:100: :clap:

**Pull request closed without merging**
